import test from 'node:test';
import assert from 'node:assert/strict';
import {createClient} from '@supabase/supabase-js';
import {createOAuthFlow,verifierStorage,safeAuthDestination} from '../src/services/oauthFlow.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
function fixture(extra={}){
 const storage=memory();let calls=0,adopted=0,seq=0,options;
 const client={auth:{signInWithOAuth:async o=>{options=o;storage.setItem('oauth-code-verifier','verifier');return {data:{url:extra.url||'https://test.supabase.co/auth/v1/authorize?provider=google&code_challenge=x&code_challenge_method=s256'}};},exchangeCodeForSession:async()=>{calls++;return extra.exchangeError?{error:{}}:{data:{session:{access_token:'a',refresh_token:'r'}}};}}};
 const args={client,sessionClient:{auth:{setSession:async tokens=>{adopted++;assert.deepEqual(tokens,{access_token:'a',refresh_token:'r'});return extra.adoptError?{error:{}}:{data:{session:{}}};}}},storage,key:'oauth',projectUrl:'https://test.supabase.co',redirectUrl:()=>extra.native?'meuagro://auth/callback':'https://farm.example/auth/callback',open:extra.open||(()=>{}),now:extra.now||(()=>1000),random:()=>`attempt-${++seq}`};
 return {flow:createOAuthFlow(args),args,storage,get calls(){return calls;},get adopted(){return adopted;},get options(){return options;},callback:(suffix='&code=code')=>(extra.native?'meuagro://auth/callback':'https://farm.example/auth/callback')+'?flow=oauth&attempt=attempt-'+seq+suffix};
}
for(const native of [true,false])test('Google '+(native?'Android':'web')+' adota sessão e destino',async()=>{const f=fixture({native});await f.flow.start('/consultor?x=1');assert.equal(f.options.provider,'google');assert.equal(f.options.options.skipBrowserRedirect,true);assert.equal(await f.flow.finish(f.callback()),'/consultor?x=1');assert.equal(f.adopted,1);assert.equal(f.storage.getItem('oauth-pending'),null);assert.equal(f.storage.getItem('oauth-code-verifier'),null);});
test('Callback duplicado troca código uma vez',async()=>{const f=fixture();await f.flow.start();await Promise.all([f.flow.finish(f.callback()),f.flow.finish(f.callback())]);assert.equal(f.calls,1);await assert.rejects(f.flow.finish(f.callback()));});
test('Retorno após reinício funciona',async()=>{const f=fixture();await f.flow.start('/inventory');assert.equal(await createOAuthFlow(f.args).finish(f.callback()),'/inventory');});
test('Cancelamento não cria sessão e permite retry',async()=>{const f=fixture();await f.flow.start();await assert.rejects(f.flow.finish(f.callback('&error=access_denied')),/não foi concluído/);assert.equal(f.adopted,0);await f.flow.start();assert.equal(await f.flow.finish(f.callback()),'/dashboard');});
test('Tentativa estranha não apaga atual',async()=>{const f=fixture();await f.flow.start();await assert.rejects(f.flow.finish(f.callback().replace('attempt-1','wrong')));assert.ok(f.storage.getItem('oauth-pending'));assert.equal(f.calls,0);});
test('Troca para senha cancela Google',async()=>{const f=fixture();await f.flow.start();f.flow.cancel();await assert.rejects(f.flow.finish(f.callback()));});
test('Nova tentativa substitui anterior',async()=>{const f=fixture();await f.flow.start();const old=f.callback();await f.flow.start();await assert.rejects(f.flow.finish(old));assert.equal(await f.flow.finish(f.callback()),'/dashboard');});
test('Tentativa expirada recusada',async()=>{let time=1000;const f=fixture({now:()=>time});await f.flow.start();time+=600001;await assert.rejects(f.flow.finish(f.callback()),/expirou/);assert.equal(f.calls,0);});
test('Tokens implícitos e ausência de código recusados',async()=>{for(const suffix of ['','#access_token=x&refresh_token=y']){const f=fixture();await f.flow.start();await assert.rejects(f.flow.finish(f.callback(suffix)));assert.equal(f.calls,0);}});
for(const url of ['https://evil.example','javascript:alert(1)','https://test.supabase.co/auth/v1/authorize?provider=google&code_challenge=x&code_challenge_method=plain'])test('URL recusada '+url,async()=>{let opened=false;const f=fixture({url,open:()=>{opened=true;}});await assert.rejects(f.flow.start());assert.equal(opened,false);assert.equal(f.storage.getItem('oauth-pending'),null);});
for(const error of ['exchangeError','adoptError'])test('Erro '+error,async()=>{const f=fixture({[error]:true});await f.flow.start();await assert.rejects(f.flow.finish(f.callback()));assert.equal(f.storage.getItem('oauth-pending'),null);});
test('Falha do navegador limpa tentativa',async()=>{const f=fixture({open:()=>{throw Error('browser');}});await assert.rejects(f.flow.start());assert.equal(f.storage.getItem('oauth-code-verifier'),null);});
test('Duplo clique é bloqueado',async()=>{let release;const f=fixture({open:()=>new Promise(r=>release=r)});const first=f.flow.start();await new Promise(r=>setTimeout(r,0));await assert.rejects(f.flow.start(),/Aguarde/);release();await first;});
for(const destination of ['https://evil.example','//evil.example','/\\evil.example','/login','/auth/callback','javascript:alert(1)'])test('Destino inseguro '+destination,()=>assert.equal(safeAuthDestination(destination),'/dashboard'));
test('Storage auxiliar não persiste tokens',()=>{const s=memory(),a=verifierStorage(s,'oauth');a.setItem('oauth','secret');assert.equal(s.getItem('oauth'),null);a.setItem('oauth-code-verifier','v');assert.equal(a.getItem('oauth-code-verifier'),'v');a.removeItem('oauth-code-verifier');assert.equal(a.getItem('oauth-code-verifier'),null);});
test('SDK real gera S256 e envia verificador no exchange',async()=>{
 const storage=memory(),key='sdk-oauth';let callback,request;
 const sdk=createClient('https://sdk.example','test-public-key',{auth:{flowType:'pkce',storageKey:key,storage:verifierStorage(storage,key),persistSession:true,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:async(url,options)=>{request=JSON.parse(options.body);assert.match(url,/grant_type=pkce/);return new Response(JSON.stringify({access_token:'access',refresh_token:'refresh',expires_in:3600,token_type:'bearer',user:{id:'test'}}),{status:200,headers:{'Content-Type':'application/json'}});}}});
 const f=createOAuthFlow({client:sdk,sessionClient:{auth:{setSession:async()=>({data:{session:{}}})}},storage,key,projectUrl:'https://sdk.example',redirectUrl:()=> 'meuagro://auth/callback',open:url=>{const u=new URL(url);assert.equal(u.searchParams.get('code_challenge_method'),'s256');assert.ok(u.searchParams.get('code_challenge').length>30);callback=u.searchParams.get('redirect_to');}});
 await f.start();assert.ok(storage.getItem(key+'-code-verifier'));await f.finish(callback+'&code=test-code');assert.equal(request.auth_code,'test-code');assert.ok(request.code_verifier.length>30);assert.equal(storage.getItem(key),null);assert.equal(storage.getItem(key+'-code-verifier'),null);await sdk.auth.stopAutoRefresh();
});
