import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {managementFixture} from './management-fixture.mjs';

test('Gestão: permissões, aprovações, carteira e indicadores',async t=>{
 const f=await managementFixture(),{db,as,commerce,command,rows,ids}=f;
 const rpc=async(name,args=[]) =>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args)).rows[0].r;
 let seller,conn,product,req,quote,order;
 const manage=(action,data={},op=randomUUID())=>rpc('management_command',[action,{seller_id:seller,...data},op]);
 const report=(filter={},offset=0,from='2026-09-01',to='2026-09-30')=>rpc('management_report',[seller,from,to,filter,offset]);
 const proposal=()=>({request_id:req,items:[{product_id:product,unit_price:100}],discount:30,freight:10,valid_until:new Date(Date.now()+86400000).toISOString(),delivery_days:2,payment_terms:'Na entrega'});
 try {
  await t.test('Migração reaplicável',async()=>await db.exec(f.migration));
  await as(1);await commerce('enable',{name:'Dono'});seller=(await commerce('create_company',{name:'Empresa gerencial'})).seller_id;
  for(const n of [2,3]){await as(1);await commerce('invite',{seller_id:seller,email:`user${n}@example.test`});const i=(await rows('commerce_invitations')).find(i=>i.email===`user${n}@example.test`);await as(n);await commerce('enable',{name:n===2?'Gestor':'Consultor'});await commerce('accept_invite',{token:i.token});}
  await as(1);product=(await command('save_product',{seller_id:seller,name:'Adubo',package_name:'Saco',base_unit:'kg',package_size:25,reference_price:100,availability:'available'})).id;
  await as(3);await command('invite_buyer',{seller_id:seller,email:'user4@example.test'});const invitation=(await rows('trade_invitations')).find(i=>i.email==='user4@example.test');
  await as(4);conn=(await command('accept_connection',{token:invitation.token,name:'Produtor teste'})).id;
  req=(await command('create_request',{connection_id:conn,delivery_address:'Fazenda 100',items:[{product_id:product,quantity:2}]})).id;
  await t.test('Produtor não acessa relatório, carteira, notas ou tabelas internas',async()=>{await assert.rejects(report());await assert.rejects(rpc('management_wallet',[seller]));await assert.rejects(rpc('management_workspace',[req]));for(const table of ['management_notes','management_approvals','management_pipeline'])await assert.rejects(rows(table));});
  await as(3);await t.test('Consultor comum não ganha acesso gerencial',async()=>{assert.deepEqual(await rpc('management_companies'),[]);await assert.rejects(report());await assert.rejects(manage('grant',{agent_id:ids[2],role:'manager'}));});
  await t.test('Notas são internas e repetição não duplica',async()=>{const op=randomUUID(),d={request_id:req,body:'Contato interno confidencial'};await manage('note',d,op);await manage('note',d,op);const w=await rpc('management_workspace',[req]);assert.equal(w.notes.length,1);assert.equal(w.notes[0].body,d.body);});
  await t.test('Retorno tem controle de versão',async()=>{await manage('followup',{request_id:req,body:'Retornar contato',due_at:'2026-01-01T12:00:00Z',expected_version:0});await assert.rejects(manage('followup',{request_id:req,body:'Sobrescrever',expected_version:0}),/mudou/);});
  await as(1);await manage('grant',{agent_id:ids[1],role:'manager',finance:false});await manage('settings',{discount_limit:10,stale_hours:48});
  await t.test('Dono acessa painel completo e alertas atuais',async()=>{const r=await report();assert.equal(r.owner,true);assert.equal(r.finance,true);assert.equal(r.team.length,3);assert.equal(r.totals.followup_due,1);assert.equal(r.queue.count,1);assert.equal((await rpc('management_wallet',[seller])).count,1);});
  await as(2);await t.test('Gestor operacional vê equipe, mas não valores privados',async()=>{const r=await report();assert.equal(r.finance,false);assert.ok(!('commission' in r.totals));assert.ok(r.team.every(a=>!('commission' in a)));assert.equal((await rows('trade_requests')).length,1);await assert.rejects(manage('grant',{agent_id:ids[2],role:'manager'}));await assert.rejects(manage('settings',{discount_limit:100,stale_hours:48}));});
  await t.test('Gestor define meta; edição obsoleta é recusada',async()=>{const data={month:'2026-09-01',agent_id:'',amount:10000,expected_version:0};await manage('goal',data);await assert.rejects(manage('goal',data),/mudou/);await manage('goal',{...data,amount:20000,expected_version:1});assert.equal((await report()).goals.items[0].amount,20000);});
  await as(3);let approval;const data=proposal(),op=randomUUID();
  await t.test('Desconto acima do limite fica interno sem alterar solicitação',async()=>{approval=await command('send_quote',data,op);assert.equal(approval.approval_pending,true);assert.deepEqual(await command('send_quote',data,op),approval);assert.equal((await rows('trade_quotes')).length,0);assert.equal((await rows('trade_requests'))[0].state,'awaiting');await assert.rejects(rpc('trade_command_before_management',['send_quote',data,randomUUID()]));});
  await as(4);await t.test('Produtor não recebe proposta ou aviso prematuro',async()=>{assert.equal((await rows('trade_quotes')).length,0);assert.equal((await rows('trade_notifications')).length,0);});
  await as(2);await t.test('Gestor recebe aviso e aprova uma única vez',async()=>{assert.ok((await rows('trade_notifications')).some(n=>n.kind==='approval_requested'));const op=randomUUID(),d={approval_id:approval.id,reason:'Desconto autorizado'};const result=await manage('approve',d,op);quote=result.id;assert.ok(quote);assert.deepEqual(await manage('approve',d,op),result);await assert.rejects(manage('approve',d));assert.equal((await rows('trade_quotes')).length,1);});
  await as(4);await t.test('Proposta aprovada chega com valores corretos',async()=>{const q=(await rows('trade_quotes'))[0];assert.equal(Number(q.total),180);order=(await command('accept_quote',{request_id:req,quote_id:quote})).id;assert.ok(order);});
  await db.exec('reset role');await db.query("update trade_orders set state='received',received_at='2026-10-01T01:00:00Z' where id=$1",[order]);
  await as(1);await t.test('Receita usa recebimento em Brasília e produto exclui frete',async()=>{const r=await report();assert.equal(r.totals.sales_total,180);assert.equal(r.products[0].revenue,170);assert.equal(r.products[0].volume,50);assert.equal(r.totals.commission,null);assert.equal(r.products[0].product_result,null);assert.equal((await report({},0,'2026-10-01','2026-10-31')).totals.sales_total,0);});
  await t.test('Transferência preserva consultor da venda aceita e registra motivo',async()=>{await manage('transfer',{connection_id:conn,expected_agent:ids[2],agent_id:ids[1],reason:'Redistribuição de atendimento'});const r=await report();assert.equal(r.team.find(a=>a.id===ids[2]).revenue,180);assert.equal(r.team.find(a=>a.id===ids[1]).customers,1);await assert.rejects(manage('transfer',{connection_id:conn,expected_agent:ids[2],agent_id:ids[0],reason:'Tela antiga'}),/mudou/);assert.ok(r.audit.some(a=>a.action==='transfer'));});
  await as(3);await t.test('Antigo responsável perde acesso interno após transferência',async()=>await assert.rejects(rpc('management_workspace',[req])));
  await as(2);await t.test('Novo responsável mantém notas e ocultação financeira',async()=>{assert.equal((await rpc('management_workspace',[req])).notes.length,1);const r=await report();assert.ok(!('product_result' in r.products[0]));});
  await as(1);await t.test('Permissão financeira é delegada explicitamente',async()=>{await manage('grant',{agent_id:ids[1],role:'manager',finance:true});await as(2);assert.equal((await report()).finance,true);await as(1);});
  await t.test('Filtros e datas inválidas são tratados',async()=>{assert.equal((await report({buyer:'inexistente',state:'received'})).queue.count,0);assert.equal((await report({product,state:'received'})).queue.count,1);await assert.rejects(report({},-1));await assert.rejects(report({},0,'2020-01-01','2026-09-30'));});
  await t.test('Mais de 50 solicitações usam paginação sem truncar contagem',async()=>{await as(4);for(let i=0;i<52;i++)await command('create_request',{connection_id:conn,delivery_address:'Fazenda 100',items:[{product_id:product,quantity:1}]});await as(1);const a=await report(),b=await report({},50);assert.equal(a.queue.count,52);assert.equal(a.queue.items.length,50);assert.equal(b.queue.items.length,2);assert.equal(new Set([...a.queue.items,...b.queue.items].map(x=>x.id)).size,52);});
  await t.test('Revogar vínculo remove gestão e concessões anteriores',async()=>{const m=(await rows('commerce_memberships')).find(m=>m.user_id===ids[1]);await commerce('end_membership',{membership_id:m.id});await as(2);assert.deepEqual(await rpc('management_companies'),[]);await assert.rejects(report());await db.exec('reset role');const row=(await rows('commerce_memberships')).find(m=>m.user_id===ids[1]);assert.equal(row.management_role,'representative');assert.equal(row.can_view_finance,false);});
  await as(null,'anon');await t.test('Anônimo não executa ações gerenciais',async()=>await assert.rejects(rpc('management_companies')));
 }finally{await db.close();}
});
