import {appShell} from '../../components/appShell.js';
import {escapeHtml as e} from '../../js/html.js';
import {navigate} from '../../js/router.js';
import {money} from '../../services/tradeService.js';
import {managementCompanies,managementReport,managementWallet,managementWorkspace,managementCommand,managementError} from '../../services/managementService.js';
const number=v=>Number(v).toLocaleString('pt-BR');
const chart=(entries,label)=>{const max=Math.max(1,...entries.map(x=>Number(x.value)));return `<ol class="sales-chart" aria-label="${e(label)}">${entries.map(x=>`<li><div class="sales-chart-label"><span>${e(x.name)}</span><strong>${money(x.value)}</strong></div><div class="sales-chart-track" aria-hidden="true"><span class="sales-chart-bar" style="width:${Math.max(0,Math.min(100,Number(x.value)/max*100))}%"></span></div></li>`).join('')}</ol>`;};
const amount=v=>v===null||v===undefined?'Pendente':money(v);
const when=v=>v?new Date(v).toLocaleString('pt-BR'):'Não informado';
const field=(id,name,label,value='',type='text',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${name}" type="${type}" value="${e(value)}" ${extra}></div>`;
const select=(id,name,label,options,value='')=>`<div class="field"><label for="${id}">${label}</label><select id="${id}" name="${name}">${options.map(([v,t])=>`<option value="${e(v)}" ${String(v)===String(value)?'selected':''}>${e(t)}</option>`).join('')}</select></div>`;
const hidden=(n,v)=>`<input type="hidden" name="${n}" value="${e(v)}">`;
const button=text=>`<button type="submit" class="button button--primary">${text}</button>`;
const states={open:'Em andamento',all:'Criadas no período',awaiting:'Nova solicitação',awaiting_buyer:'Aguardando produtor',quoted:'Proposta enviada',revision_requested:'Revisão solicitada',confirmed:'Aguardando entrega',awaiting_receipt:'Aguardando recebimento',delivery_issue:'Divergência na entrega',received:'Recebidas no período',declined:'Recusadas pelo produtor',cancelled:'Canceladas',rejected:'Recusadas pelo vendedor',stale:'Sem movimentação',followup_due:'Retorno vencido',quote_expiring:'Proposta vence em 48h',quoted_valid:'Propostas abertas válidas',to_deliver:'Pedidos a entregar'};
const approvalStatus={pending:'Aguardando aprovação',approved:'Aprovada e enviada',rejected:'Recusada',superseded:'Substituída ou invalidada'};
export async function renderManagement({session}){
 const app=document.querySelector('#app'),params=new URLSearchParams(location.search),today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 let companies=[],company,report,wallet,busy=false,disposed=false;const retries=new Map();
 const from=params.get('from')||today.slice(0,7)+'-01',to=params.get('to')||today,offset=Math.max(0,Number(params.get('offset'))||0),walletOffset=Math.max(0,Number(params.get('walletOffset'))||0),walletSearch=params.get('walletSearch')||'';
 const filter={agent:params.get('agent')||'',product:params.get('product')||'',buyer:params.get('buyer')||'',state:params.get('state')||'open'};
 const url=extra=>'/consultor/gestao?'+new URLSearchParams({seller:company.id,from,to,...filter,...extra});
 const shell=html=>appShell({session,title:'Gestão da empresa',activeNav:'commerce',content:`<div class="commerce-page manager-page">${html}</div>`});
 const notice=(message,error=false)=>{const n=app.querySelector('#manager-feedback');if(n){n.hidden=!message;n.textContent=message;n.className=error?'form-message form-message--error':'form-message form-message--success';}};
 const options=()=>report.team.filter(a=>a.active).map(a=>[a.id,a.name]);
 function paint(){
  if(disposed)return;
  if(!company){app.innerHTML=shell('<section class="commerce-card"><h2>Gestão da empresa</h2><p>Esta área é exclusiva do dono e dos gestores autorizados de uma empresa. Seu acesso de consultor continua disponível.</p><a class="button button--secondary" href="/consultor" data-link>Meu espaço</a></section>');return;}
  const t=report.totals,companyGoal=report.goals.items.find(g=>!g.agent_id),conversion=t.quote_requests?number(t.converted_requests/t.quote_requests*100)+'%':'Sem propostas';
  let html=`<div id="manager-feedback" role="status" hidden></div><section class="commerce-hero"><p class="section-eyebrow">${report.owner?'Dono da empresa':'Gestor'} • ${e(company.name)}</p><h2>Uma visão da sua equipe</h2><p>Resultados, negociações e próximos passos em um só lugar.</p><form data-manager-filter class="manager-filters">${select('mg-company','seller','Empresa',companies.map(c=>[c.id,c.name]),company.id)}${field('mg-from','from','Início',from,'date','required')}${field('mg-to','to','Fim',to,'date','required')}${button('Atualizar painel')}</form></section>`;
  const metric=(title,value,state)=>`<a class="commerce-card manager-metric" href="${url({state,offset:0})}#manager-queue" data-link><span>${title}</span><strong>${value}</strong><small>Ver negociações →</small></a>`;
  html+=`<div class="commerce-grid">${metric('Vendas recebidas',money(t.sales_total),'received')}${metric('Propostas abertas válidas',money(t.open_quotes),'quoted_valid')}${metric('Pedidos a entregar',t.to_deliver,'to_deliver')}${metric('Aguardando recebimento',t.to_receive,'awaiting_receipt')}</div><section class="commerce-card"><p>Vendas no intervalo anterior equivalente: <strong>${money(t.previous_sales)}</strong>. ${t.previous_sales>0?'Variação: '+number((t.sales_total/t.previous_sales-1)*100)+'%.':'Sem base anterior para variação percentual.'}</p><p>Conversão: <strong>${conversion}</strong> (${t.converted_requests} de ${t.quote_requests} solicitações criadas no período que tiveram proposta). Revisões não contam como novas oportunidades.</p><p>Vendas pela data de recebimento em Brasília. Carteira, propostas abertas e alertas representam a posição atual, inclusive negociações antigas.</p>${report.finance?`<p>Comissões: ${amount(t.commission)} • Custos informados: ${amount(t.cost)} • Resultado: ${amount(t.result)}</p>${t.missing_financials?`<p>${t.missing_financials} venda(s) sem apuração completa.</p>`:''}`:'<p>Seu acesso é operacional. Custos, comissões e resultados financeiros privados não são exibidos.</p>'}</section>`;
  html+=`<div class="commerce-grid manager-alerts">${metric('Sem movimentação',t.stale,'stale')}${metric('Retorno vencido',t.followup_due,'followup_due')}${metric('Propostas vencendo em 48h',t.quote_expiring,'quote_expiring')}${metric('Problemas de entrega',t.delivery_issues,'delivery_issue')}</div>`;
  html+=`<section class="commerce-card"><h2>Vendas por consultor</h2><p>Até dez maiores valores recebidos no período. Consulte a equipe completa na tabela abaixo.</p>${chart(report.team.filter(a=>a.revenue>0).slice(0,10).map(a=>({name:a.name,value:a.revenue})),'Vendas recebidas por consultor')}${report.totals.received_count?'':'<p>Ainda não há vendas recebidas neste período.</p>'}</section>`;
  html+=`<section class="commerce-card"><h2>Metas do mês ${report.goals.month.slice(0,7)}</h2><p>Recebido no mês completo: ${money(report.goals.company_sales)}. Meta da empresa: ${companyGoal?money(companyGoal.amount):'Não definida'}${companyGoal?.amount>0?' • '+number(report.goals.company_sales/companyGoal.amount*100)+'% atingida':''}.</p><p>As metas usam o mês da data inicial do painel, independentemente do intervalo escolhido.</p><form data-manager-command="goal" class="manager-filters">${select('mg-goal-agent','agent_id','Meta para',[['','Empresa'],...options()])}${field('mg-goal-amount','amount','Valor da meta (R$)','','number','required min="0" max="1000000000000" step="0.01"')}${button('Salvar meta')}</form></section>`;
  html+=`<section class="commerce-card"><h2>Desempenho da equipe</h2><p>Vendas e comissões ficam com o consultor no aceite. A conversão é atribuída a quem enviou a primeira proposta da solicitação criada no período. O tempo médio considera a primeira resposta efetiva, em horas corridas, atribuída a quem respondeu; solicitações sem resposta não entram na média.</p><div class="manager-table" role="region" aria-label="Comparação dos consultores" tabindex="0"><table><thead><tr><th>Consultor</th><th>Carteira</th><th>Abertas</th><th>Vendas recebidas</th><th>Conversão</th><th>Primeira resposta</th><th>Meta mensal</th>${report.finance?'<th>Comissão</th>':''}</tr></thead><tbody>${report.team.map(a=>`<tr><th scope="row">${e(a.name)}${a.active?'':' • Inativo'}</th><td>${a.customers}</td><td>${a.open_requests}</td><td>${money(a.revenue)}</td><td>${a.quoted?number(a.converted/a.quoted*100)+'%':'—'} (${a.converted}/${a.quoted})</td><td>${a.response_hours===null?'—':number(a.response_hours)+' h'}</td><td>${a.goal===null?'Não definida':money(a.goal)}<br>${money(a.month_sales)} recebido</td>${report.finance?`<td>${amount(a.commission)}</td>`:''}</tr>`).join('')}</tbody></table></div></section>`;
  html+=`<section class="commerce-card" id="manager-queue"><h2>Fila de negociações</h2><form data-manager-queue class="manager-filters">${select('mg-agent','agent','Consultor',[['','Todos'],...report.team.map(a=>[a.id,a.name])],filter.agent)}${select('mg-product','product','Produto',[['','Todos'],...report.catalog.map(p=>[p.id,p.name])],filter.product)}${field('mg-buyer','buyer','Produtor',filter.buyer)}${select('mg-state','state','Situação',Object.entries(states),filter.state)}${button('Filtrar negociações')}</form><p>${report.queue.count} negociação(ões). Filtros desta lista não alteram os indicadores gerais. Recebidas usa o período de recebimento; Criadas no período usa a criação. As demais situações mostram a posição atual.</p>${report.queue.items.map(q=>`<article class="commerce-row"><div><strong>${e(q.buyer_name)}</strong><p>${e(q.agent_name)} • ${e(states[q.stage]||q.stage)}${q.approval_pending?' • Desconto em aprovação':''}</p><p>${q.order_total!==null?money(q.order_total):q.quote_total!==null?money(q.quote_total):'Sem proposta'} • Última movimentação: ${when(q.last_activity)}</p>${q.attention?`<p class="manager-attention">${e(q.attention)}</p>`:''}<p>Próxima ação: ${e(q.next_action||'Não definida')}${q.due_at?' • '+when(q.due_at):''}</p></div><div class="commerce-actions"><a class="button button--secondary" href="/consultor/negociacoes?request=${q.id}" data-link>Abrir negociação</a><a class="button button--primary" href="/consultor/acompanhamento?request=${q.id}" data-link>Acompanhamento interno</a></div></article>`).join('')||'<p>Nenhuma negociação encontrada.</p>'}<nav class="commerce-actions" aria-label="Páginas das negociações">${offset?`<a class="button button--secondary" href="${url({offset:Math.max(0,offset-50)})}#manager-queue" data-link>Anterior</a>`:''}${offset+50<report.queue.count?`<a class="button button--secondary" href="${url({offset:offset+50})}#manager-queue" data-link>Próxima</a>`:''}</nav></section>`;
  html+=`<section class="commerce-card"><h2>Aprovações de desconto</h2><p>${report.approvals.length} pendente(s). Aprovar publica a proposta para o produtor com os termos exibidos. A justificativa fica no acompanhamento interno.</p>${report.approvals.map(a=>`<article class="commerce-card"><h3>Solicitação ${e(a.request_id)}</h3><p>Produtos: ${money(a.summary.subtotal)} • Desconto: ${money(a.summary.discount)} • Frete: ${money(a.summary.freight)} • Total: ${money(a.summary.total)}</p>${a.summary.items.map(i=>`<p>${e(i.name)} × ${number(i.quantity)}: ${money(i.line_total)}</p>`).join('')}<p>Validade: ${when(a.summary.valid_until)} • Entrega: ${a.summary.delivery_days} dia(s) • Pagamento: ${e(a.summary.payment_terms)}</p>${a.summary.notes?`<p class="manager-note">Observações: ${e(a.summary.notes)}</p>`:''}<form data-manager-command="approve">${hidden('approval_id',a.id)}${field('mg-approval-'+a.id,'reason','Justificativa','','text','required minlength="5" maxlength="500"')}<div class="commerce-actions">${button('Aprovar e enviar proposta')}<button class="button button--secondary" type="submit" data-command="reject">Recusar desconto</button></div></form></article>`).join('')||'<p>Nenhuma aprovação pendente.</p>'}</section>`;
  html+=`<section class="commerce-card" id="manager-wallet"><h2>Carteira de produtores</h2><form data-manager-wallet class="manager-filters">${field('mg-wallet-search','walletSearch','Buscar produtor na carteira',walletSearch)}${button('Buscar na carteira')}</form><p>${wallet.count} produtor(es). Transferir muda o responsável pela carteira e pelos atendimentos em andamento, preservando a atribuição das vendas já aceitas.</p>${wallet.items.map(c=>`<details class="commerce-card"><summary>${e(c.buyer_name)} • ${e(c.agent_name)}</summary><form data-manager-command="transfer">${hidden('connection_id',c.id)}${hidden('expected_agent',c.agent_id)}${select('mg-transfer-'+c.id,'agent_id','Novo responsável',options(),c.agent_id)}${field('mg-transfer-reason-'+c.id,'reason','Motivo da transferência','','text','required minlength="5" maxlength="500"')}${button('Transferir carteira')}</form></details>`).join('')}<nav class="commerce-actions" aria-label="Páginas da carteira">${walletOffset?`<a class="button button--secondary" href="${url({walletSearch,walletOffset:Math.max(0,walletOffset-50)})}#manager-wallet" data-link>Carteira anterior</a>`:''}${walletOffset+50<wallet.count?`<a class="button button--secondary" href="${url({walletSearch,walletOffset:walletOffset+50})}#manager-wallet" data-link>Próxima carteira</a>`:''}</nav></section>`;
  html+=`<section class="commerce-card"><h2>Análise de produtos</h2><p>Receita após desconto, sem frete. Volumes separados por embalagem e unidade.${report.finance?' Resultado do produto = receita do produto menos seu custo de aquisição; não deduz entrega, comissão ou outras despesas.':''}</p>${chart(report.products.slice(0,5).map(p=>({name:p.name+' • '+p.package_name+' '+p.package_size+' '+p.base_unit,value:p.revenue})),'Cinco produtos com maior receita no período')}<p>Gráfico: até cinco produtos com maior receita. A lista abaixo apresenta todos os produtos vendidos.</p>${report.products.map(p=>`<article class="commerce-row"><div><strong>${e(p.name)}</strong><p>${e(p.package_name)} • ${number(p.package_size)} ${e(p.base_unit)} • ${number(p.packages)} embalagem(ns) • ${number(p.volume)} ${e(p.base_unit)}</p><p>Receita: ${money(p.revenue)} • Desconto médio ponderado: ${number(p.discount_percent)}%</p>${report.finance?`<p>Resultado do produto: ${amount(p.product_result)}${p.revenue>0&&p.product_result!==null?' • Margem: '+number(p.product_result/p.revenue*100)+'%':''}${p.missing?' • Custos incompletos':''}</p>`:''}</div></article>`).join('')||'<p>Nenhuma venda recebida no período.</p>'}</section><details class="commerce-card"><summary>Negociações encerradas e motivos registrados</summary><p>Até 100 solicitações mais recentes, criadas no período. Motivos são os textos registrados pelas partes, sem classificação automática.</p>${report.losses.map(l=>`<article class="commerce-row"><div><strong>${e(l.buyer_name)} • ${e(l.agent_name)}</strong><p>${l.items.map(i=>e(i.name)).join(', ')}</p><p>${e(l.reason||'Sem motivo informado')}</p></div></article>`).join('')||'<p>Nenhum encerramento encontrado.</p>'}</details>`;
  if(report.owner)html+=`<section class="commerce-card"><h2>Permissões e limites</h2><form data-manager-command="settings" class="manager-filters">${field('mg-limit','discount_limit','Desconto sem aprovação (%)',report.settings.discount_limit,'number','required min="0" max="100" step="0.01"')}${field('mg-stale','stale_hours','Atenção após quantas horas sem movimentação?',report.settings.stale_hours,'number','required min="1" max="720" step="1"')}${button('Salvar limites')}</form><p>O limite considera o campo Desconto da proposta, não alterações do preço de referência do catálogo. Dono e gestores podem aprovar descontos. Por padrão, 100% preserva o fluxo anterior.</p>${report.team.some(a=>a.role!=='owner'&&a.active)?`<form data-manager-command="grant">${select('mg-permission-agent','agent_id','Representante para alterar acesso',report.team.filter(a=>a.role!=='owner'&&a.active).map(a=>[a.id,a.name+' • '+(a.role==='manager'?'Gestor':'Consultor')]))}${select('mg-role','role','Papel',[['representative','Consultor'],['manager','Gestor']])}${select('mg-finance','finance','Pode consultar custos e comissões?',[['false','Não'],['true','Sim']])}${button('Salvar permissões')}</form>`:'<p>Convide representantes pelo cadastro da empresa para delegar acesso de gestor.</p>'}</section>`;
  html+=`<details class="commerce-card"><summary>Histórico gerencial recente</summary><p>Últimas 50 ações. As notas internas podem ser lidas no acompanhamento da negociação.</p>${report.audit.map(a=>`<p>${when(a.created_at)} • ${e(a.actor)} • ${e(({grant:'Permissões alteradas',settings:'Limites alterados',goal:'Meta alterada',transfer:'Carteira transferida',note:'Nota interna',followup:'Próxima ação alterada',approve:'Proposta aprovada',reject:'Desconto recusado',request_approval:'Aprovação solicitada'})[a.action]||'Atualização')}${a.details.reason?' • '+e(a.details.reason):''}</p>`).join('')}</details>`;
  app.innerHTML=shell(html);
  if(['#manager-queue','#manager-wallet'].includes(location.hash))requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView({block:'start'}));
 }
 async function load(){[report,wallet]=await Promise.all([managementReport(company.id,from,to,filter,offset),managementWallet(company.id,walletSearch,walletOffset)]);}
 const submit=async event=>{
  const form=event.target.closest('form');if(!form)return;event.preventDefault();if(busy||!form.reportValidity())return;
  const data=Object.fromEntries(new FormData(form));
  if(form.hasAttribute('data-manager-filter')){navigate('/consultor/gestao?'+new URLSearchParams(data));return;}
  if(form.hasAttribute('data-manager-queue')){navigate(url({...data,offset:0})+'#manager-queue');return;}
  if(form.hasAttribute('data-manager-wallet')){navigate(url({...data,walletOffset:0})+'#manager-wallet');return;}
  const action=event.submitter?.dataset.command||form.dataset.managerCommand;if(!action)return;
  data.seller_id=company.id;
  if(action==='goal'){data.month=report.goals.month;data.expected_version=report.goals.items.find(g=>(g.agent_id||'')===data.agent_id)?.version||0;}
  const key=action+JSON.stringify(data);if(!retries.has(key))retries.set(key,crypto.randomUUID());
  busy=true;const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);let saved=false;notice('Salvando…');
  try{await managementCommand(action,data,retries.get(key));saved=true;await load();if(!disposed){retries.clear();paint();notice(action==='approve'?'Proposta aprovada e enviada ao produtor.':'Alteração salva.');}}
  catch(error){if(!disposed)notice(saved?'A alteração foi salva. Reabra a tela antes de repetir.':managementError(error),true);}
  finally{busy=false;buttons.forEach(b=>b.disabled=false);}
 };
 app.innerHTML=shell('<p role="status">Carregando gestão…</p>');
 try{companies=await managementCompanies();company=companies.find(c=>c.id===params.get('seller'))||companies[0];if(company)await load();paint();}
 catch(error){if(!disposed)app.innerHTML=shell(`<section class="commerce-card"><h2>Não foi possível abrir a gestão</h2><p role="alert">${e(managementError(error))}</p><a class="button button--secondary" href="/consultor" data-link>Meu espaço</a></section>`);}
 app.addEventListener('submit',submit);return()=>{disposed=true;app.removeEventListener('submit',submit);};
}
export async function renderManagementWorkspace({session}){
 const app=document.querySelector('#app'),request=new URLSearchParams(location.search).get('request');let data,busy=false,disposed=false;const retries=new Map();
 const shell=html=>appShell({session,title:'Acompanhamento interno',activeNav:'commerce',content:`<div class="commerce-page">${html}</div>`});
 const paint=()=>{if(disposed)return;const f=data.followup,date=f?.due_at?new Date(new Date(f.due_at).getTime()-new Date(f.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
 app.innerHTML=shell(`<a class="button button--secondary" href="/consultor/negociacoes?request=${e(request)}" data-link>Voltar à negociação</a><section class="commerce-card"><h2>Somente para a equipe</h2><p>O produtor não recebe estas notas nem os lembretes internos. ${data.notes.length===100?'Exibindo as últimas 100 notas.':''}</p><div id="workspace-feedback" role="status"></div><form data-workspace="followup">${field('ws-next','body','Próxima ação',f?.next_action||'','text','maxlength="500"')}${field('ws-due','due_at','Data e hora do retorno',date,'datetime-local')}${button('Salvar próxima ação')}</form></section><section class="commerce-card"><h2>Notas internas</h2><form data-workspace="note"><div class="field"><label for="ws-body">Nova nota interna</label><textarea id="ws-body" name="body" required maxlength="2000" rows="3"></textarea></div>${button('Adicionar nota')}</form>${data.notes.map(n=>`<article class="commerce-row"><div><strong>${e(n.author)}</strong><p>${when(n.created_at)}</p><p class="manager-note">${e(n.body)}</p></div></article>`).join('')||'<p>Nenhuma nota interna.</p>'}</section><section class="commerce-card"><h2>Solicitações de desconto</h2>${data.approvals.map(a=>`<p>${when(a.created_at)} • ${approvalStatus[a.status]}${a.reason?' • '+e(a.reason):''}</p>`).join('')||'<p>Nenhuma solicitação.</p>'}</section>`);};
 const submit=async event=>{const form=event.target.closest('[data-workspace]');if(!form)return;event.preventDefault();if(busy||!form.reportValidity())return;const action=form.dataset.workspace,value=Object.fromEntries(new FormData(form));value.request_id=request;if(action==='followup'){value.expected_version=data.followup?.version||0;value.due_at=value.due_at?new Date(value.due_at).toISOString():'';}
 const key=action+JSON.stringify(value);if(!retries.has(key))retries.set(key,crypto.randomUUID());busy=true;let saved=false;
 try{await managementCommand(action,value,retries.get(key));saved=true;data=await managementWorkspace(request);if(!disposed){retries.clear();paint();app.querySelector('#workspace-feedback').textContent='Acompanhamento salvo.';}}
 catch(error){if(!disposed)app.querySelector('#workspace-feedback').textContent=saved?'Salvo. Reabra a tela antes de repetir.':managementError(error);}finally{busy=false;}};
 app.innerHTML=shell('<p>Carregando acompanhamento…</p>');try{data=await managementWorkspace(request);paint();}catch(error){if(!disposed)app.innerHTML=shell(`<p role="alert">${e(managementError(error))}</p>`);}app.addEventListener('submit',submit);return()=>{disposed=true;app.removeEventListener('submit',submit);};
}
